suppressPackageStartupMessages(library(dbarts))
grDevices::pdf(NULL)
set.seed(20260824); n <- 40L; nTest <- 10L
x <- matrix(runif(n*3L),n,3L); colnames(x) <- c("x1","x2","x3")
xTest <- matrix(runif(nTest*3L),nTest,3L); colnames(xTest) <- colnames(x)
yG <- as.numeric(2*x[,1]-x[,2]+rnorm(n,0,0.3))
counts <- t(rmultinom(n, size=10L, prob=c(0.4,0.35,0.25))); colnames(counts) <- c("a","b","c")
yBin <- rbinom(n,1L,plogis(2*(x[,1]-0.5))); wInt <- rep(2L,n)
ct <- function(...) do.call(dbartsControl, utils::modifyList(list(n.chains=1L,n.threads=1L,n.trees=4L,n.burn=3L,n.samples=5L,keepTrees=TRUE,keepTrainingFits=TRUE),list(...)))
p <- function(lab, ex) { r <- tryCatch(withCallingHandlers(eval(ex), warning=function(w) invokeRestart("muffleWarning")),
    error=function(e) structure(conditionMessage(e), class="err"))
  if (inherits(r,"err")) cat(sprintf("%-52s ERROR: %s\n", lab, substr(as.character(r),1,110)))
  else cat(sprintf("%-52s OK %s %s\n", lab, paste(class(r),collapse="/"), if(!is.null(dim(r))) paste(dim(r),collapse="x") else paste0("len",length(r)))) }
sm <- dbarts(dbartsData(x, counts=counts), family="multinomial", control=ct(), verbose=FALSE); invisible(sm$run(3L,5L))
sa <- dbarts(x, yG, control=ct(), forests=list(forest(n.trees=3L), forest(basis=x[,2,drop=FALSE], n.trees=3L)), verbose=FALSE); invisible(sa$run(3L,5L))
sh <- dbarts(x, yG, control=ct(), variance=~x1, verbose=FALSE); invisible(sh$run(3L,5L))
sw <- dbarts(x, yBin, family="logistic", weights=wInt, control=ct(), verbose=FALSE); rw <- sw$run(3L,5L)
sg <- dbarts(x, yG, control=ct(), verbose=FALSE); rg <- sg$run(3L,5L)
cat("=== corrected multinomial channel probes ===\n")
p("mn$predict(xTest)",                         quote(sm$predict(xTest)))
p("mn$setCategoryOffset(matrix(0,n,3))",       quote(sm$setCategoryOffset(matrix(0,n,3L))))
p("mn$setCategoryTestOffset(matrix(0,10,3))",  quote({sm$setTestPredictor(xTest); sm$setCategoryTestOffset(matrix(0,nTest,3L))}))
p("mn$setState(sm$state)",                     quote(sm$setState(sm$state)))
p("mn$getLatents()",                           quote(sm$getLatents()))
p("mn$getTrees()",                             quote(sm$getTrees()))
p("mn$plotTree(1L,1L,1L)",                     quote(sm$plotTree(1L,1L,1L)))
p("mn$getCalibration(1L)",                     quote(sm$getCalibration(1L)))
p("mn$getForestFits(1L)",                      quote(sm$getForestFits(1L)))
p("mn$getForestVariableCounts(1L)",            quote(sm$getForestVariableCounts(1L)))
cat("=== corrected amplitude probes ===\n")
p("amp$setForestBasis(2L, x[,3,drop=FALSE])",  quote(sa$setForestBasis(2L, x[,3,drop=FALSE])))
p("amp$setForestBasis(1L, x[,3,drop=FALSE])",  quote(sa$setForestBasis(1L, x[,3,drop=FALSE])))
p("amp$setForestBasis(2L, ~zz) [formula env]", quote({zz <- factor(rbinom(n,1L,.5)); sa$setForestBasis(2L, ~zz)}))
p("amp$setState(sa$state)",                    quote(sa$setState(sa$state)))
p("amp$getForestAmplitudes()",                 quote(sa$getForestAmplitudes()))
p("amp$predictForests(xTest)",                 quote(sa$predictForests(xTest)))
cat("=== corrected hetero / wlogistic probes ===\n")
p("het$setForestBasis(1L, x[,3,drop=FALSE])",  quote(sh$setForestBasis(1L, x[,3,drop=FALSE])))
p("het$setForestWeights(1L, runif(n))",        quote(sh$setForestWeights(1L, runif(n))))
p("het$getLatents()",                          quote(sh$getLatents()))
p("het$setState(sh$state)",                    quote(sh$setState(sh$state)))
p("wl$getLatents()",                           quote(sw$getLatents()))
p("wl$setWeights(rep(3L,n))",                  quote(sw$setWeights(rep(3L,n))))
p("wl$setResponse(yBin)",                      quote(sw$setResponse(yBin)))
p("wl$setState(sw$state)",                     quote(sw$setState(sw$state)))
p("gauss$getLatents(rg)  [wrong arg, as census]", quote(sg$getLatents(rg)))
p("gauss$getLatents()",                        quote(sg$getLatents()))
p("gauss$setState(sg$storeState())",           quote(sg$setState(sg$storeState())))
p("gauss$setState(sg$state)",                  quote(sg$setState(sg$state)))
