suppressPackageStartupMessages(library(dbarts))
grDevices::pdf(NULL)
set.seed(2); nTest<-12L
xTest <- matrix(runif(nTest*3),nTest,3); colnames(xTest)<-c("x1","x2","x3")
p <- function(lab, ex) {
  r <- tryCatch(withCallingHandlers(eval(ex), warning=function(w) invokeRestart("muffleWarning")),
                error=function(e) structure(conditionMessage(e), class="err"))
  if (inherits(r,"err")) cat(sprintf("%-46s ERROR: %s\n", lab, as.character(r)))
  else cat(sprintf("%-46s OK %s %s\n", lab, paste(class(r),collapse="/"), paste(dim(r), collapse="x")))
}
f <- readRDS(file.path(Sys.getenv("D"),"f-fresh.rds"))
cat("--- reloaded 1-chain bart, nothing called before ---\n")
p("plotTree(f, treeNum=1L)",       quote(plotTree(f, treeNum=1L)))
p("extract(f, type='trees')",      quote(extract(f, type="trees")))
p("predict(f, xTest)",             quote(predict(f, xTest)))
p("plotTree(f, treeNum=1L) again", quote(plotTree(f, treeNum=1L)))
f2 <- readRDS(file.path(Sys.getenv("D"),"f-fresh.rds"))
cat("--- reloaded again: predict first, then plotTree ---\n")
p("predict(f2, xTest)",            quote(predict(f2, xTest)))
p("plotTree(f2, treeNum=1L)",      quote(plotTree(f2, treeNum=1L)))
p("f2$fit$plotTree(1L)",           quote(f2$fit$plotTree(1L)))
p("f2$fit$getTrees()",             quote(f2$fit$getTrees()))
g <- readRDS(file.path(Sys.getenv("D"),"g-fresh.rds"))
cat("--- reloaded 2-chain bart ---\n")
p("plotTree(g, treeNum=1L, chainNum=1L, sampleNum=1L)", quote(plotTree(g, treeNum=1L, chainNum=1L, sampleNum=1L)))
p("extract(g, type='trees')",      quote(extract(g, type="trees")))
s <- readRDS(file.path(Sys.getenv("D"),"s-fresh.rds"))
cat("--- reloaded dbartsSampler ---\n")
p("s$plotTree(1L)",                quote(s$plotTree(1L)))
p("plotTree(s, 1L)",               quote(plotTree(s, 1L)))
p("s$getTrees()",                  quote(s$getTrees()))
p("s$predict(xTest)",              quote(s$predict(xTest)))
p("s$run(0L,1L)",                  quote(s$run(0L,1L)))
p("extract(s)",                    quote(extract(s)))
