suppressPackageStartupMessages(library(dbarts)); grDevices::pdf(NULL)
set.seed(5); n<-40L; nTest<-8L
x <- matrix(runif(n*3L),n,3L); colnames(x)<-c("x1","x2","x3")
xTest <- matrix(runif(nTest*3L),nTest,3L); colnames(xTest)<-colnames(x)
y <- as.numeric(2*x[,1]-x[,2]+rnorm(n,0,0.3))
f  <- bart2(x,y,n.trees=3L,n.samples=4L,n.burn=3L,n.chains=1L,n.threads=1L,keepTrees=TRUE,keepTrainingFits=TRUE,test=xTest,verbose=FALSE,seed=1L)
f2 <- bart2(x,y,n.trees=3L,n.samples=4L,n.burn=3L,n.chains=2L,n.threads=1L,keepTrees=TRUE,keepTrainingFits=TRUE,test=xTest,verbose=FALSE,seed=1L)
p <- function(lab, ex){ r <- tryCatch(withCallingHandlers(eval(ex),warning=function(w) invokeRestart("muffleWarning")),
    error=function(e) structure(conditionMessage(e),class="err"))
  if (inherits(r,"err")) cat(sprintf("%-50s ERROR: %s\n", lab, substr(as.character(r),1,105)))
  else cat(sprintf("%-50s OK %s %s\n", lab, paste(class(r),collapse="/"), if(is.data.frame(r)) paste0(nrow(r),"x",ncol(r)) else if(!is.null(dim(r))) paste(dim(r),collapse="x") else paste0("len",length(r)))) }
cat("=== positional type=trees ===\n")
p("extract(f, 'trees')",            quote(extract(f, "trees")))
p("extract(f, 'trees', 'train')",   quote(extract(f, "trees", "train")))
cat("=== plotTree partial-matching into sampleNum/chainNum ===\n")
p("plotTree(f, treeNum=1L, sample=2L)",  quote(plotTree(f, treeNum=1L, sample=2L)))
p("plotTree(f, treeNum=1L, sampleNum=2L)", quote(plotTree(f, treeNum=1L, sampleNum=2L)))
p("plotTree(f2, treeNum=1L, chain=2L)",  quote(plotTree(f2, treeNum=1L, chain=2L)))
p("plotTree(f2, treeNum=1L)  [2 chains, no chainNum]", quote(plotTree(f2, treeNum=1L)))
p("plotTree(f, treeNum=1L, sampleNum=99L)", quote(plotTree(f, treeNum=1L, sampleNum=99L)))
cat("=== residuals argument collisions ===\n")
p("residuals(f, sample='train')",  quote(residuals(f, sample="train")))
p("residuals(f, type='ppd')",      quote(residuals(f, type="ppd")))
cat("=== predict: documented 'Not used in predict' dots ===\n")
p("predict(f, xTest, sample='test')",  quote(predict(f, xTest, sample="test")))
p("predict(f, xTest, contribution=TRUE)", quote(predict(f, xTest, contribution=TRUE)))
p("predict(f, xTest, nonsense=1)",     quote(predict(f, xTest, nonsense=1)))
cat("=== extract dots on non-trees types ===\n")
p("extract(f, type='ev', treeNums=1L)", quote(extract(f, type="ev", treeNums=1L)))
p("extract(f, type='ev', nonsense=1)",  quote(extract(f, type="ev", nonsense=1)))
cat("=== plot on keepTrainingFits=FALSE ===\n")
f3 <- bart2(x,y,n.trees=3L,n.samples=4L,n.burn=3L,n.chains=1L,n.threads=1L,keepTrainingFits=FALSE,verbose=FALSE,seed=1L)
p("plot(f3)",                          quote(plot(f3)))
p("extract(f3, sample='train')",       quote(extract(f3, sample="train")))
