suppressPackageStartupMessages({library(dbarts)})
set.seed(20260824); n<-40L; nTest<-12L
x <- matrix(runif(n*3),n,3); colnames(x)<-c("x1","x2","x3")
xTest <- matrix(runif(nTest*3),nTest,3); colnames(xTest)<-colnames(x)
y <- as.numeric(2*x[,1]-x[,2]+rnorm(n,0,0.3))
grp <- factor(sample(letters[1:3], n, TRUE))
f  <- bart2(x,y,n.trees=3L,n.samples=4L,n.burn=3L,n.chains=1L,n.threads=1L,keepTrees=TRUE,keepTrainingFits=TRUE,test=xTest,verbose=FALSE,seed=1L)
f2 <- bart2(x,y,n.trees=3L,n.samples=4L,n.burn=3L,n.chains=2L,n.threads=1L,keepTrees=TRUE,keepTrainingFits=TRUE,test=xTest,verbose=FALSE,seed=1L)
rf <- rbart_vi(x,y,group.by=grp,n.trees=3L,n.samples=6L,n.burn=4L,n.chains=1L,n.threads=1L,keepTrees=TRUE,verbose=FALSE)
p <- function(lab, ex) {
  r <- tryCatch(withCallingHandlers(eval(ex), warning=function(w) invokeRestart("muffleWarning")),
                error=function(e) paste0("ERROR: ", conditionMessage(e)))
  if (is.character(r) && length(r)==1 && startsWith(r,"ERROR")) cat(sprintf("%-58s %s\n", lab, r))
  else cat(sprintf("%-58s OK  %s [%s]\n", lab, paste(class(r),collapse="/"),
      if (is.data.frame(r)) paste0(nrow(r),"x",ncol(r)," cols=", paste(colnames(r),collapse=",")) else paste(dim(r) %||% length(r), collapse="x")))
}
`%||%` <- function(a,b) if (is.null(a)) b else a
cat("=== extract(type='trees') on bart, keepTrees=TRUE ===\n")
p("extract(f, type='trees')",                       quote(extract(f, type="trees")))
p("extract(f, type='trees', sample='train')",       quote(extract(f, type="trees", sample="train")))
p("extract(f, type='trees', sample='test')",        quote(extract(f, type="trees", sample="test")))
p("extract(f, type='trees', combineChains=FALSE)",  quote(extract(f, type="trees", combineChains=FALSE)))
p("extract(f, type='trees', combineChains=TRUE)",   quote(extract(f, type="trees", combineChains=TRUE)))
p("extract(f, type='trees', forest=1L)",            quote(extract(f, type="trees", forest=1L)))
p("extract(f, type='trees', contribution=TRUE)",    quote(extract(f, type="trees", contribution=TRUE)))
p("extract(f, type='trees', treeNums=1L)",          quote(extract(f, type="trees", treeNums=1L)))
p("extract(f, type='trees', chainNums=1L)",         quote(extract(f, type="trees", chainNums=1L)))
p("extract(f, type='trees', sampleNums=1L)",        quote(extract(f, type="trees", sampleNums=1L)))
p("extract(f, type='trees', newdata=xTest)",        quote(extract(f, type="trees", newdata=xTest)))
p("extract(f2, type='trees', chainNums=2L)",        quote(extract(f2, type="trees", chainNums=2L)))
cat("\n=== extract(type='trees') on rbart ===\n")
p("extract(rf, type='trees')",                      quote(extract(rf, type="trees")))
p("extract(rf, type='trees', sample='train')",      quote(extract(rf, type="trees", sample="train")))
p("extract(rf, type='trees', combineChains=FALSE)", quote(extract(rf, type="trees", combineChains=FALSE)))
p("extract(rf, type='trees', treeNums=1L)",         quote(extract(rf, type="trees", treeNums=1L)))
p("extract(rf, type='trees', newdata=xTest)",       quote(extract(rf, type="trees", newdata=xTest)))
cat("\n=== residuals / fitted argument collisions ===\n")
p("residuals(f, sample='train')",                   quote(residuals(f, sample="train")))
p("residuals(f, combineChains=FALSE)",              quote(residuals(f, combineChains=FALSE)))
p("fitted(f, combineChains=FALSE)",                 quote(fitted(f, combineChains=FALSE)))
p("fitted(f, type='ev', sample='test', combineChains=FALSE)", quote(fitted(f, type="ev", sample="test", combineChains=FALSE)))
cat("\n=== partial matching into the generic ===\n")
p("extract(f, type='ev', samp='test')",             quote(extract(f, type="ev", samp="test")))
p("extract(f, ty='ev')",                            quote(extract(f, ty="ev")))
p("predict(f, xTest, comb=FALSE)",                  quote(predict(f, xTest, comb=FALSE)))
cat("\n=== extract(type='trees') on a fit whose sampler was NOT kept ===\n")
f3 <- bart2(x,y,n.trees=3L,n.samples=4L,n.burn=3L,n.chains=1L,n.threads=1L,keepTrees=FALSE,keepSampler=FALSE,verbose=FALSE,seed=1L)
p("extract(f3, type='trees')",                      quote(extract(f3, type="trees")))
f4 <- bart2(x,y,n.trees=3L,n.samples=4L,n.burn=3L,n.chains=1L,n.threads=1L,keepTrees=FALSE,keepSampler=TRUE,verbose=FALSE,seed=1L)
p("extract(f4, type='trees')  [keepSampler only]",  quote(extract(f4, type="trees")))
