suppressPackageStartupMessages({library(dbarts); library(posterior)})
set.seed(11); n<-40L; nTest<-8L
x <- matrix(runif(n*3L),n,3L); colnames(x)<-c("x1","x2","x3")
xTest <- matrix(runif(nTest*3L),nTest,3L); colnames(xTest)<-colnames(x)
y <- as.numeric(2*x[,1]-x[,2]+rnorm(n,0,0.3))
yb <- rbinom(n,1L,plogis(2*(x[,1]-0.5)))
grp <- factor(sample(letters[1:3],n,TRUE)); grpT <- factor(sample(letters[1:3],nTest,TRUE), levels=letters[1:3])
d <- function(v) if (is.null(dim(v))) paste0("len",length(v)) else paste(dim(v),collapse="x")
dn <- function(v){z<-dimnames(v); if(is.null(z)) "NULL" else paste(vapply(z,function(q) if(is.null(q)) "NULL" else paste0("{",paste(head(q,3),collapse=","),"}"),character(1)),collapse=" | ")}
p <- function(lab, ex){ r <- tryCatch(withCallingHandlers(eval(ex),warning=function(w) invokeRestart("muffleWarning")),
    error=function(e) structure(conditionMessage(e),class="err"))
  if (inherits(r,"err")) cat(sprintf("%-50s ERROR: %s\n", lab, substr(as.character(r),1,100)))
  else cat(sprintf("%-50s %s %s  dn=%s\n", lab, paste(class(r),collapse="/"), d(r), dn(r))) }
b <- function(...) bart2(x, y, n.trees=4L,n.samples=6L,n.burn=4L,n.threads=1L,keepTrees=TRUE,
                         keepTrainingFits=TRUE,test=xTest,verbose=FALSE,seed=1L, ...)
f1 <- b(n.chains=1L); f2 <- b(n.chains=2L); f2u <- b(n.chains=2L, combineChains=FALSE)
cat("=== bart.Rd Value layout: chain-major collapse and dimnames ===\n")
cat("f2 (2 chains, combined):  yhat.train", d(f2$yhat.train), " sigma", d(f2$sigma), " varcount", d(f2$varcount), " dn(varcount)=", dn(f2$varcount), "\n")
cat("f2u (2 chains, uncomb):   yhat.train", d(f2u$yhat.train), " sigma", d(f2u$sigma), " varcount", d(f2u$varcount), "\n")
cat("f1 (1 chain):             yhat.train", d(f1$yhat.train), " sigma", d(f1$sigma), "\n")
cat("f2$n.chains:", if (is.null(f2[["n.chains"]])) "ABSENT" else f2$n.chains,
    "| f2u$n.chains:", if (is.null(f2u[["n.chains"]])) "ABSENT" else f2u$n.chains, "\n")
cat("dimnames(f1$yhat.train):", dn(f1$yhat.train), "\n")
cat("=== chain-major row order (sigma[r] pairs yhat.train[r,]) ===\n")
cat("f2 sigma == c(f2u chain1, chain2)?",
    isTRUE(all.equal(as.numeric(f2$sigma), as.numeric(t(f2u$sigma)))) ||
    isTRUE(all.equal(as.numeric(f2$sigma), as.numeric(f2u$sigma))), "\n")
cat("f2u sigma dim:", d(f2u$sigma), "; f2 sigma[1:3]:", round(f2$sigma[1:3],4), "; f2u sigma[1,1:3]:", round(f2u$sigma[1,1:3],4), "\n")
cat("=== extract shapes ===\n")
p("extract(f2,'ev') combined",        quote(extract(f2, type="ev")))
p("extract(f2,'ev') uncombined",      quote(extract(f2, type="ev", combineChains=FALSE)))
p("extract(f2,'loglik') combined",    quote(extract(f2, type="loglik")))
p("extract(f2,'loglik') uncombined",  quote(extract(f2, type="loglik", combineChains=FALSE)))
p("extract(f2,'loglik', sample='test')", quote(extract(f2, type="loglik", sample="test")))
cat("=== predict.glm synonyms (bart.Rd:201) ===\n")
p("extract(f1, type='response')",     quote(extract(f1, type="response")))
p("extract(f1, type='link')",         quote(extract(f1, type="link")))
p("predict(f1, xTest, type='response')", quote(predict(f1, xTest, type="response")))
p("fitted(f1, type='link')",          quote(fitted(f1, type="link")))
p("residuals(f1, type='link')",       quote(residuals(f1, type="link")))
cat("=== ci.level (bart.Rd:216) ===\n")
p("fitted(f1, ci.level=0.9)",         quote(fitted(f1, ci.level=0.9)))
p("predict(f1, xTest, ci.level=0.9)", quote(predict(f1, xTest, ci.level=0.9)))
cat("  colnames:", paste(colnames(fitted(f1, ci.level=0.9)), collapse=","), "\n")
cat("=== summary (summary.bart.Rd) ===\n")
s <- summary(f2); cat("class:", class(s), " elements:", paste(names(s),collapse=","), "\n")
print(s$stats)
fh <- bart2(x, y, variance=~x1, n.trees=4L,n.samples=6L,n.burn=4L,n.chains=2L,n.threads=1L,
            keepTrees=TRUE,keepTrainingFits=TRUE,verbose=FALSE,seed=1L)
cat("hetero summary vars:", paste(summary(fh)$stats$variable, collapse=","), "\n")
cat("hetero summary(vars='s.train') nvars:", nrow(summary(fh, vars="s.train")$stats), "\n")
cat("summary(f2, vars='nosuchfield') stats:", is.null(summary(f2, vars="nosuchfield")$stats), "\n")
cat("as_draws_array formals:", paste(names(formals(getS3method("as_draws_array","bart"))), collapse=","), "\n")
p("as_draws_array(f2)",               quote(as_draws_array(f2)))
p("as_draws_df(f2)",                  quote(as_draws_df(f2)))
p("as_draws_array(f2, vars='varcount')", quote(as_draws_array(f2, vars="varcount")))
cat("=== extract(type='trees', newdata=) n column (bart.Rd:263) ===\n")
t0 <- extract(f1, type="trees"); t1 <- extract(f1, type="trees", newdata=xTest)
cat("n totals: train", sum(t0$n[t0$var==-1]), " newdata", sum(t1$n[t1$var==-1]), " (nrow train/test:", n, nTest, ")\n")
cat("=== rbart layout ===\n")
r2 <- rbart_vi(x, y, group.by=grp, group.by.test=grpT, test=xTest, n.trees=4L,n.samples=6L,n.burn=4L,
               n.chains=2L,n.threads=1L,keepTrees=TRUE,verbose=FALSE)
cat("rbart n.chains:", if(is.null(r2[["n.chains"]])) "ABSENT" else r2$n.chains, " length(fit):", length(r2$fit), "\n")
cat("ranef:", d(r2$ranef), " dn:", dn(r2$ranef), " tau:", d(r2$tau), " yhat.train:", d(r2$yhat.train), "\n")
p("extract(r2, type='ranef')",        quote(extract(r2, type="ranef")))
p("fitted(r2, type='ranef')",         quote(fitted(r2, type="ranef")))
p("predict(r2, xTest, group.by=grpT, type='ranef')", quote(predict(r2, xTest, group.by=grpT, type="ranef")))
