suppressPackageStartupMessages(library(dbarts)); grDevices::pdf(NULL)
set.seed(7); nTest<-10L
xTest <- matrix(runif(nTest*3L),nTest,3L); colnames(xTest)<-c("x1","x2","x3")
zs <- rbinom(nTest,1L,0.5)
p <- function(lab, ex){ r <- tryCatch(withCallingHandlers(eval(ex), warning=function(w) invokeRestart("muffleWarning")),
    error=function(e) structure(conditionMessage(e), class="err"))
  if (inherits(r,"err")) cat(sprintf("%-50s ERROR: %s\n", lab, substr(as.character(r),1,120)))
  else cat(sprintf("%-50s OK %s %s\n", lab, paste(class(r),collapse="/"), if(!is.null(dim(r))) paste(dim(r),collapse="x") else paste0("len",length(r)))) }
D <- Sys.getenv("D")
cat("=== after documented storeState() + saveRDS, fresh session ===\n")
sg <- readRDS(file.path(D,"sg.rds")); p("gauss sampler $predict",   quote(sg$predict(xTest)))
sa2<- readRDS(file.path(D,"sa2.rds"))
p("amplitude sampler $getForestAmplitudes", quote(sa2$getForestAmplitudes()))
p("amplitude sampler $predictForests",      quote(sa2$predictForests(xTest)))
p("amplitude sampler $getTrees",            quote(sa2$getTrees()))
fG <- readRDS(file.path(D,"fG.rds"))
p("bart fit predict",         quote(predict(fG, xTest)))
p("bart fit extract(trees)",  quote(extract(fG, type="trees")))
p("bart fit plotTree",        quote(plotTree(fG, treeNum=1L)))
fA <- readRDS(file.path(D,"fA.rds"))
p("amplitude fit extract(type='forest')", quote(extract(fA, type="forest")))
p("amplitude fit predict(type='forest')", quote(predict(fA, cbind(x1=xTest[,1],x2=xTest[,2]), type="forest")))
p("amplitude fit predict(ev)",            quote(predict(fA, data.frame(x1=xTest[,1],x2=xTest[,2],z=zs))))
p("amplitude fit plotTree",               quote(plotTree(fA, treeNum=1L)))
fM <- readRDS(file.path(D,"fM.rds"))
p("multinomial fit predict",  quote(predict(fM, xTest)))
p("multinomial fit extract",  quote(extract(fM)))
fR <- readRDS(file.path(D,"fR.rds"))
p("rbart fit predict",        quote(predict(fR, xTest, group.by=factor(sample(letters[1:3],nTest,TRUE), levels=letters[1:3]))))
p("rbart fit extract(trees)", quote(extract(fR, type="trees")))
p("rbart fit plotTree",       quote(plotTree(fR, treeNum=1L)))
fH <- readRDS(file.path(D,"fH.rds"))
p("hurdle fit predict",       quote(predict(fH, xTest)))
p("hurdle fit extract",       quote(extract(fH)))
p("hurdle fit fitted",        quote(fitted(fH)))
