suppressPackageStartupMessages(library(dbarts)); grDevices::pdf(NULL)
set.seed(3); n<-40L; nTest<-8L
x <- matrix(runif(n*3L),n,3L); colnames(x)<-c("x1","x2","x3")
xTest <- matrix(runif(nTest*3L),nTest,3L); colnames(xTest)<-colnames(x)
y <- as.numeric(2*x[,1]-x[,2]+rnorm(n,0,0.3))
s <- dbarts(x,y,control=dbartsControl(n.chains=1L,n.threads=1L,n.trees=4L,n.burn=3L,n.samples=5L,keepTrees=TRUE))
invisible(s$run())
p <- function(lab, ex){ r <- tryCatch(withCallingHandlers({z<-utils::capture.output(v<-eval(ex)); v},
      warning=function(w) invokeRestart("muffleWarning")), error=function(e) structure(conditionMessage(e),class="err"))
  if (inherits(r,"err")) cat(sprintf("%-44s ERROR: %s\n", lab, substr(as.character(r),1,105)))
  else cat(sprintf("%-44s OK %s %s\n", lab, paste(class(r),collapse="/"), if(!is.null(dim(r))) paste(dim(r),collapse="x") else paste0("len",length(r)))) }
cat("=== dbartsSampler through the fit-object generics ===\n")
for (g in c("predict","fitted","residuals","summary","print","plot"))
  p(paste0(g,"(sampler)"), bquote(.(as.name(g))(s)))
p("extract(sampler)",              quote(extract(s)))
p("extract(sampler, 'predictors')",quote(extract(s, "predictors")))
p("extract(sampler, type='ev')",   quote(extract(s, type="ev")))
p("plotTree(sampler, 1L)",         quote(plotTree(s, 1L)))
p("survivalProbabilities(sampler)",quote(survivalProbabilities(s, times=1)))
cat("\n=== xbart result ===\n")
xb <- xbart(x,y,n.samples=5L,n.reps=2L,n.test=5L,n.burn=c(4L,3L),n.trees=c(4L,8L),k=c(1,2,3),n.threads=1L,method="k-fold",verbose=FALSE)
cat("class:", class(xb), " dim:", paste(dim(xb),collapse="x"), " dimnames:", paste(names(dimnames(xb)),collapse=","), "\n")
for (g in c("predict","extract","fitted","residuals","summary","print","plot","plotTree"))
  p(paste0(g,"(xbart)"), bquote(.(as.name(g))(xb)))
cat("\n=== pdbart / pd2bart ===\n")
pd <- pdbart(x,y,xind=1:2,ntree=4L,ndpost=6L,nskip=4L,verbose=FALSE)
p2 <- pd2bart(x,y,xind1=1L,xind2=2L,ntree=4L,ndpost=6L,nskip=4L,verbose=FALSE)
for (g in c("predict","extract","fitted","residuals","summary","print"))
  p(paste0(g,"(pdbart)"), bquote(.(as.name(g))(pd)))
p("plot(pdbart)", quote(plot(pd)))
p("plot(pd2bart)", quote(plot(p2)))
