suppressPackageStartupMessages(library(dbarts))
cat("=== formals of every registered fit-class method ===\n")
gens <- c("predict","extract","fitted","residuals","summary","print","plot","plotTree","survivalProbabilities")
cls  <- c("bart","rbart","bartMultinomial","bartOrdinal","bartNegbin","bartHurdle","dbartsSampler")
for (g in gens) for (cc in cls) {
  m <- tryCatch(getS3method(g,cc,optional=TRUE), error=function(e) NULL)
  if (!is.null(m)) cat(sprintf("%-22s %-18s (%s)\n", g, cc, paste(names(formals(m)), collapse=", ")))
}
set.seed(13); n<-60L; nTest<-8L
x <- matrix(runif(n*3L),n,3L); colnames(x)<-c("x1","x2","x3")
xTest <- matrix(runif(nTest*3L),nTest,3L); colnames(xTest)<-colnames(x)
yO <- ordered(c("lo","mid","hi")[1L+(x[,1]>0.33)+(x[,1]>0.66)], levels=c("lo","mid","hi"))
yN <- rnbinom(n,size=5L,mu=exp(0.4*(x[,1]-0.5)))
yM <- factor(sample(c("a","b","c"),n,TRUE), levels=c("a","b","c"))
b <- function(y,fam) bart2(x,y,family=fam,n.trees=4L,n.samples=6L,n.burn=4L,n.chains=2L,n.threads=1L,
     keepTrees=TRUE,keepTrainingFits=TRUE,test=xTest,verbose=FALSE,seed=1L)
fO<-b(yO,"ordinal"); fN<-b(yN,"nbinom"); fM<-b(yM,"multinomial")
sh <- function(v) if(is.null(dim(v))) paste0("len",length(v)) else paste(dim(v),collapse="x")
cat("\n=== silently-swallowed arguments (same result with and without) ===\n")
chk <- function(lab, a, bq) {
  ra <- tryCatch(eval(a), error=function(e) structure(conditionMessage(e),class="err"))
  rb <- tryCatch(eval(bq), error=function(e) structure(conditionMessage(e),class="err"))
  if (inherits(rb,"err")) cat(sprintf("%-56s REFUSED: %s\n", lab, substr(as.character(rb),1,70)))
  else cat(sprintf("%-56s %s -> %s  identical=%s\n", lab, sh(ra), sh(rb), identical(ra,rb)))
}
chk("extract(fM, combineChains=FALSE)", quote(extract(fM)), quote(extract(fM, combineChains=FALSE)))
chk("extract(fO, combineChains=FALSE)", quote(extract(fO)), quote(extract(fO, combineChains=FALSE)))
chk("extract(fN, combineChains=FALSE)", quote(extract(fN)), quote(extract(fN, combineChains=FALSE)))
chk("fitted(fM, sample='test')",        quote(fitted(fM)),  quote(fitted(fM, sample="test")))
chk("fitted(fO, sample='test')",        quote(fitted(fO)),  quote(fitted(fO, sample="test")))
chk("fitted(fN, sample='test')",        quote(fitted(fN)),  quote(fitted(fN, sample="test")))
chk("fitted(fM, ci.level=0.9)",         quote(fitted(fM)),  quote(fitted(fM, ci.level=0.9)))
chk("fitted(fO, ci.level=0.9)",         quote(fitted(fO)),  quote(fitted(fO, ci.level=0.9)))
chk("fitted(fN, ci.level=0.9)",         quote(fitted(fN)),  quote(fitted(fN, ci.level=0.9)))
chk("predict(fO, xTest, ci.level=0.9)", quote(predict(fO,xTest)), quote(predict(fO,xTest,ci.level=0.9)))
chk("predict(fN, xTest, ci.level=0.9)", quote(predict(fN,xTest)), quote(predict(fN,xTest,ci.level=0.9)))
chk("predict(fM, xTest, ci.level=0.9)", quote(predict(fM,xTest)), quote(predict(fM,xTest,ci.level=0.9)))
chk("residuals(fM, type='bart')",       quote(residuals(fM)), quote(residuals(fM, type="bart")))
chk("residuals(fO, type='bart')",       quote(residuals(fO)), quote(residuals(fO, type="bart")))
chk("residuals(fN, type='bart')",       quote(residuals(fN)), quote(residuals(fN, type="bart")))
chk("predict(fM, xTest, combineChains=FALSE)", quote(predict(fM,xTest)), quote(predict(fM,xTest,combineChains=FALSE)))
chk("predict(fO, xTest, combineChains=FALSE)", quote(predict(fO,xTest)), quote(predict(fO,xTest,combineChains=FALSE)))
chk("predict(fN, xTest, combineChains=FALSE)", quote(predict(fN,xTest)), quote(predict(fN,xTest,combineChains=FALSE)))
chk("extract(fM, forest=1L)",           quote(extract(fM)), quote(extract(fM, forest=1L)))
chk("summary(fM, vars='sigma')",        quote(summary(fM)), quote(summary(fM, vars="sigma")))
