suppressPackageStartupMessages({library(dbarts); library(posterior)}); grDevices::pdf(NULL)
set.seed(13); n<-60L; nTest<-8L
x <- matrix(runif(n*3L),n,3L); colnames(x)<-c("x1","x2","x3")
xTest <- matrix(runif(nTest*3L),nTest,3L); colnames(xTest)<-colnames(x)
yO <- ordered(c("lo","mid","hi")[1L+(x[,1]>0.33)+(x[,1]>0.66)], levels=c("lo","mid","hi"))
yN <- rnbinom(n,size=5L,mu=exp(0.4*(x[,1]-0.5)))
yH <- ifelse(runif(n)<0.3,0,rlnorm(n, meanlog=0.2*(x[,1]-0.5)))
yM <- factor(sample(c("a","b","c"),n,TRUE), levels=c("a","b","c"))
b <- function(y, fam, ...) bart2(x, y, family=fam, n.trees=4L,n.samples=6L,n.burn=4L,n.chains=2L,n.threads=1L,
      keepTrees=TRUE,keepTrainingFits=TRUE,verbose=FALSE,seed=1L, ...)
fO <- b(yO,"ordinal", test=xTest); fN <- b(yN,"nbinom", test=xTest); fH <- b(yH,"hurdle.lognormal"); fM <- b(yM,"multinomial", test=xTest)
p <- function(lab, ex){ r <- tryCatch(withCallingHandlers(eval(ex),warning=function(w) invokeRestart("muffleWarning")),
    error=function(e) structure(conditionMessage(e),class="err"))
  if (inherits(r,"err")) cat(sprintf("%-52s ERROR: %s\n", lab, substr(as.character(r),1,105)))
  else cat(sprintf("%-52s OK %s %s\n", lab, paste(class(r),collapse="/"), if(!is.null(dim(r))) paste(dim(r),collapse="x") else paste0("len",length(r)))) }
cat("=== hurdle type aliases (bart2.Rd:322) ===\n")
p("extract(fH, type='link')",  quote(extract(fH, type="link")))
p("extract(fH, type='log')",   quote(extract(fH, type="log")))
p("predict(fH, xTest, type='log')", quote(predict(fH, xTest, type="log")))
p("fitted(fH, type='log')",    quote(fitted(fH, type="log")))
cat("formals(fitted.bartHurdle):", paste(names(formals(getS3method("fitted","bartHurdle"))),collapse=","), "\n")
cat("formals(predict.bartHurdle):", paste(names(formals(getS3method("predict","bartHurdle"))),collapse=","), "\n")
p("fitted(fH, ci.level=0.9)",  quote(fitted(fH, ci.level=0.9)))
p("predict(fH, xTest, ci.level=0.9)", quote(predict(fH, xTest, ci.level=0.9)))
cat("=== ordinal / nbinom summary contents ===\n")
cat("ordinal summary vars:", paste(summary(fO)$stats$variable, collapse=","), "\n")
cat("nbinom  summary vars:", paste(summary(fN)$stats$variable, collapse=","), "\n")
cat("multinom summary vars:", paste(summary(fM)$stats$variable, collapse=","), "\n")
cat("hurdle summary class:", class(summary(fH)), "\n")
cat("=== ordinal 'link' alias (bart2.Rd:316) ===\n")
p("extract(fO, type='link')",  quote(extract(fO, type="link")))
p("extract(fO, type='response')", quote(extract(fO, type="response")))
cat("=== loglik channel on own-class families ===\n")
for (nm in c("fO","fN","fH","fM")) p(paste0("extract(",nm,", type='loglik')"), bquote(extract(.(as.name(nm)), type="loglik")))
cat("=== sample-validation message consistency ===\n")
p("extract(fO, sample='bogus')", quote(extract(fO, sample="bogus")))
p("extract(fM, sample='bogus')", quote(extract(fM, sample="bogus")))
p("extract(fN, sample='bogus')", quote(extract(fN, sample="bogus")))
p("extract(fH, sample='bogus')", quote(extract(fH, sample="bogus")))
fG <- bart2(x, rnorm(n), n.trees=4L,n.samples=6L,n.burn=4L,n.chains=1L,n.threads=1L,keepTrees=TRUE,keepTrainingFits=TRUE,verbose=FALSE,seed=1L)
p("extract(fG, sample='bogus')  [bart]", quote(extract(fG, sample="bogus")))
p("fitted(fG, sample='bogus')   [bart]", quote(fitted(fG, sample="bogus")))
cat("=== own-class n.chains / combineChains ===\n")
for (nm in c("fO","fN","fM")) { o <- get(nm); cat(nm, "n.chains:", o$n.chains, " yhat.train:", paste(dim(o$yhat.train),collapse="x"), "\n") }
cat("fH n.chains:", if(is.null(fH[["n.chains"]])) "ABSENT" else fH$n.chains, "\n")
p("extract(fO, combineChains=FALSE)", quote(extract(fO, combineChains=FALSE)))
p("extract(fM, combineChains=FALSE)", quote(extract(fM, combineChains=FALSE)))
p("extract(fN, combineChains=FALSE)", quote(extract(fN, combineChains=FALSE)))
p("extract(fH, combineChains=FALSE)", quote(extract(fH, combineChains=FALSE)))
cat("=== print methods ===\n")
for (nm in c("fO","fN","fM","fH")) { cat("--", nm, "--\n"); print(get(nm)) }
