#!/bin/sh

export SHLIB="dbarts"`R CMD config SHLIB_EXT`
if [ -f src/Makevars ]; then
  (cd src; make -f Makevars clean)
else
  (cd src; make -f Makevars.in clean)
fi

rm -rf a.out.dSYM
rm -rf autom4te.cache
rm -f config.log
rm -f config.status
rm -f src/Makevars

